---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      bash -n *.sh
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: BLUEMIX_USER
    type: text
    value: ${BLUEMIX_USER}
  - name: BLUEMIX_PASSWORD
    type: secure
    value: ${BLUEMIX_PASSWORD}
  - name: BLUEMIX_ACCOUNT
    type: secure
    value: ${BLUEMIX_ACCOUNT}
  - name: CLUSTER_NAME
    type: text
    value: ${CLUSTER_NAME}
  - name: API_KEY
    type: secure
    value: ${API_KEY}
  jobs:
  - name: Deploy ISTIO
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: Pipeline
    script: |
      #!/bin/bash
      curl -SL https://github.com/istio/istio/releases/download/0.1.6/istio-0.1.6-linux.tar.gz | tar xzf -
      mv istio-0.1.6 istio
      kubectl apply -f istio/install/kubernetes/istio-rbac-alpha.yaml
      kubectl apply -f istio/install/kubernetes/istio.yaml
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api-integration.stage1.ng.bluemix.net/v1/messaging/webhook/publish
